blank_issues_enabled: false

contact_links:
  - name: â“ Start a discussion or ask a question.
    url: https://github.com/spiral/roadrunner-plugins/discussions
    about: Please ask and answer questions here.
  - name: ğŸ›, ğŸ‘·â€â™‚ï¸ File a bug or feature request.
    url: https://github.com/spiral/roadrunner-plugins/issues
    about: Bugs, Feature requests.